In [2]:
import numpy as np

In [8]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
b = np.array([[1],
              [2],
              [3],
              [4]])
b

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.dot(a, b)

array([[30],
       [70]])

In [11]:
a @ b

array([[30],
       [70]])